### ISSUE TITLE
Комп версия для первых двух блоков

### ISSUE THREAD

**Issue by kdubasov** [consult-ui/landing-client#2]
Сейчас по дизайну апрувнули только первые 2 блока и они есть только для комп версии, в будущем картинки скорее всего заменим гифками или видосами, пока что просто вставим картинки
Пытаться верстать максимально резиново
Библиотеки в deps ставить лучше по согласованию, чем их меньше тем лучше
Ссылка на макет: скину в личку как михан мне скинет

**Comment by Vlad1slav1vanov** [comment]
https://github.com/consult-ui/landing-client/commit/f77f2e1c609ab38e7a996de531273ef4437a284d
